/* eslint-disable no-restricted-globals */

// This service worker can be customized!
// See https://developers.google.com/web/tools/workbox/modules
// for the list of available Workbox modules, or add any other
// code you'd like.
// You can also remove this file if you'd prefer not to use a
// service worker, and the Workbox build step will be skipped.

import { clientsClaim } from 'workbox-core';
import { ExpirationPlugin } from 'workbox-expiration';
import { precacheAndRoute, createHandlerBoundToURL } from 'workbox-precaching';
import { registerRoute } from 'workbox-routing';
import { StaleWhileRevalidate } from 'workbox-strategies';
import { initializeApp } from 'firebase/app';
import { onMessage } from 'firebase/messaging';
import {
  getMessaging,
  onBackgroundMessage,
  isSupported,
} from 'firebase/messaging/sw';

clientsClaim();

// Precache all of the assets generated by your build process.
// Their URLs are injected into the manifest variable below.
// This variable must be present somewhere in your service worker file,
// even if you decide not to use precaching. See https://cra.link/PWA
precacheAndRoute(self.__WB_MANIFEST);

// Set up App Shell-style routing, so that all navigation requests
// are fulfilled with your index.html shell. Learn more at
// https://developers.google.com/web/fundamentals/architecture/app-shell
const fileExtensionRegexp = new RegExp('/[^/?]+\\.[^/]+$');
registerRoute(
  // Return false to exempt requests from being fulfilled by index.html.
  ({ request, url }) => {
    // If this isn't a navigation, skip.
    if (request.mode !== 'navigate') {
      return false;
    } // If this is a URL that starts with /_, skip.

    if (url.pathname.startsWith('/_')) {
      return false;
    } // If this looks like a URL for a resource, because it contains // a file extension, skip.

    if (url.pathname.match(fileExtensionRegexp)) {
      return false;
    } // Return true to signal that we want to use the handler.

    return true;
  },
  createHandlerBoundToURL(process.env.PUBLIC_URL + '/index.html'),
);

// An example runtime caching route for requests that aren't handled by the
// precache, in this case same-origin .png requests like those from in public/
registerRoute(
  // Add in any other file extensions or routing criteria as needed.
  ({ url }) =>
    url.origin === self.location.origin && url.pathname.endsWith('.png'), // Customize this strategy as needed, e.g., by changing to CacheFirst.
  new StaleWhileRevalidate({
    cacheName: 'images',
    plugins: [
      // Ensure that once this runtime cache reaches a maximum size the
      // least-recently used images are removed.
      new ExpirationPlugin({ maxEntries: 50 }),
    ],
  }),
);

// This allows the web app to trigger skipWaiting via
// registration.waiting.postMessage({type: 'SKIP_WAITING'})
self.addEventListener('message', (event) => {
  if (event.data && event.data.type === 'SKIP_WAITING') {
    self.skipWaiting();
  }
});

// Any other custom service worker logic can go here.

// const firebaseConfig = {
//   apiKey: process.env.REACT_APP_API_KEY,
//   authDomain: process.env.REACT_APP_AUTH_DOMAIN,
//   projectId: process.env.REACT_APP_PROJECT_ID,
//   storageBucket: process.env.REACT_APP_STORAGE_BUCKET,
//   messagingSenderId: process.env.REACT_APP_MESSAGING_SENDER_ID,
//   appId: process.env.REACT_APP_APP_ID,
//   measurementId: process.env.REACT_APP_MEASUREMENT_ID,
// };

// // Initialize Firebase
// const firebaseApp = initializeApp(firebaseConfig);

// // messaging 객체가 지원하는지 판단하는 메서드 isSupported() -> promise 리턴해준다.
// isSupported().then((result) => {
//   console.log('isSupported():: ', result);
//   if (result) {
//     const messaging = getMessaging(firebaseApp);
//     console.log('messaging:: ', messaging);
//     onMessage(messaging, (payload) => {
//       // 앱이 포그라운드 상태일 때,
//       // Handle incoming messages. Called when:
//       // - a message is received while the app has focus
//       // - the user clicks on an app notification created by a service worker
//       //   `messaging.onBackgroundMessage` handler
//       // Retrieve an instance of Firebase Messaging so that it can handle background messages.
//       console.log('Message received. ', payload);
//       // ...
//     });

//     onBackgroundMessage(messaging, (payload) => {
//       console.log(
//         '[firebase-messaging-sw.js] Received background message ',
//         payload,
//       );
//       // Customize notification here
//       const notificationTitle = 'Background Message Title';
//       const notificationOptions = {
//         body: 'Background Message body.',
//       };

//       self.registration.showNotification(
//         notificationTitle,
//         notificationOptions,
//       );
//     });
//   }
// });
